import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <nav>
        <ul>
          <li><Link href="/">Index page</Link></li>
          <li><Link href="/time">Current time page</Link></li>
        </ul>
      </nav>
        {children}
      </body>
    </html>
  );
}
